version: "3"
services:
  ufire-nacos:
    image: ufire-nacos
    container_name: ufire-nacos
    hostname: ufire-nacos
    networks:
      netwaork:
        ipv4_address: 172.66.66.66
    restart: always
    #指定服务运行的端口
    ports:
      - "8848:8848"
networks:
  netwaork:
    external:
      name: ufire-network


