version: "3"
services:
  ufire-nacos:
    image: ufire-nacos
    container_name: ufire-nacos
    hostname: ufire-nacos
    networks:

    restart: always
    #指定服务运行的端口
    ports:
      - "8848:8848"
networks:
  ufire-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
