server:
  port: 8848
  tomcat:
    basedir: logs
spring:
  redis:
    port: 6379
    password: 123456
    cluster:
      nodes: 172.66.66.2,172.66.66.3,172.66.66.4,
    database: 14
    jedis.pool.max-idle: 20
    jedis.pool.min-idle: 5
    jedis.pool.max-active: 100
    jedis.pool.max-wait: 1000
    jedis.pool:max-active: 20
    sentinel.master: mymaster
    sentinel.nodes: 172.66.66.22:26379,172.66.66.23:26379,172.66.66.24:26379,
