server:
  port: 8848
  tomcat:
    basedir: logs
#spring:
#  redis:
#    database: 6
#    max-idle: 20
#    min-idle: 5
#    max-active: 100
#    max-wait: 1000
#    sentinel.master: mymaster
#    sentinel.nodes: 8.136.110.11:26380,8.136.110.11:26381,8.136.110.11:26382
#    password: 123456
spring:
  redis:
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
    sentinel:
      master: mymaster
      nodes: 8.136.110.11:26379,8.136.110.11:26380,8.136.110.11:26381